const Config = require('./config');
const Utils = require('./utils');

/**
 * An immutable object which represents a player of a game.
 */
class Player {
  /**
   * Points generated by the player.
   * @type {Point[]}
   * @member points
   * @memberof Player
   */

  /**
   * Secrets of the player. Must be kept hidden from others until the end of
   * the game.
   * @type {BigInt[]}
   * @member secrets
   * @memberof Player
   */

  /**
   * List of card IDs which are in the hand of the player.
   * @type {number[]}
   * @member cardsInHand
   * @memberof Player
   */

  constructor({ points, secrets, cardsInHand = [] } = {}) {
    if (points || secrets) {
      // None of the properties shall be auto-generated
      this.points = points || [];
      this.secrets = secrets || [];
    } else {
      // Properties should be auto-generated
      this.points = Utils.getRandomPoints();
      this.secrets = Utils.getRandomSecrets();
    }

    this.cardsInHand = cardsInHand;
  }

  /**
   * Returns the hashes of the player's secrets.
   * @param {string} [algorithm] Hash algorithm to be used.
   * @returns {string[]}
   */
  getSecretHashes(algorithm = Config.hashAlgorithm) {
    return Utils.getSecretHashes(this.secrets, algorithm);
  }
}

module.exports = Player;
